export const UPDATE_MAIN_TIME = "UPDATE_MAIN_TIME";
export const UPDATE_BREAK_TIME = "UPDATE_BREAK_TIME";
export const DECREASE_TIMER = "DECREASE_TIMER";
export const TOGGLE_IS_BREAK = "TOGGLE_IS_BREAK";
export const CHANGE_TIMER = "CHANGE_TIMER";
export const START_TIMER = "START_TIMER";
export const PAUSE_TIMER = "PAUSE_TIMER";
